apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./guestbook-ui-deployment.yaml
- ./guestbook-ui-svc.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: guestbook-ui
  patch: |-
    - op: add
      path: /spec/selector/matchLabels/foo
      value: bar

    - op: add
      path: /spec/template/metadata/labels/foo
      value: bar
