apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour 
  namespace: argo-cd
spec:
  project: default
  source:
    chart: contour 
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "18.2.9"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: projectcontour
  syncPolicy:
    syncOptions:
    - CreateNamespace=true