apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argo-cd
spec:
  project: default
  source:
    chart: metallb
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "6.3.7"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metallb-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true