apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argo-cd
spec:
  project: default
  source:
    chart: metallb
    repoURL: oci://registry-1.docker.io/bitnamicharts
    targetRevision: "6.3.7"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metallb-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true