apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argo-cd
spec:
  project: default
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: "0.28.1"
    helm:
      values: |
        server:
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
            tls:
              secretName: vault-tls
              hosts:
                - vault.khalin.local
            hosts:
              - host: vault.khalin.local
                paths: []
          ha:
            raft:
              enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
  syncPolicy:
    syncOptions:
    - CreateNamespace=true