apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argo-cd
spec:
  project: default
  source:
    chart: pihole
    repoURL: https://mojo2600.github.io/pihole-kubernetes
    targetRevision: "2.24"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: pihole
  syncPolicy:
    syncOptions:
    - CreateNamespace=true