apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard
  namespace: argocd
spec:
  project: default
  source:
    chart: adguard-home
    repoURL: https://helm-charts.rm3l.org
    targetRevision: 0.17
  destination:
    server: "https://kubernetes.default.svc"
    namespace: adguard
  syncPolicy:
    syncOptions:
    - CreateNamespace=true