apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical
  namespace: argo-cd
spec:
  project: default
  source:
    chart: infisical
    repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts
    targetRevision: "0.4.2"
    helm:
      values: |
        ingress:
          ingressClassName: contour
          hostName: &hostName infisical.khalin.local
          tls:
            hosts: 
              - *hostName
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infisical
  syncPolicy:
    syncOptions:
    - CreateNamespace=true