apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argo-cd
spec:
  project: default
  source:
    chart: pihole
    repoURL: https://mojo2600.github.io/pihole-kubernetes
    targetRevision: "2.24"
    helm:
      values: |
        persistentVolumeClaim:
          enabled: true

        serviceWeb:
          loadBalancerIP: 192.168.178.252
          annotations:
            metallb.universe.tf/allow-shared-ip: pihole-svc
          type: LoadBalancer

        serviceDns:
          loadBalancerIP: 192.168.178.252
          annotations:
            metallb.universe.tf/allow-shared-ip: pihole-svc
          type: LoadBalancer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: pihole
  syncPolicy:
    syncOptions:
    - CreateNamespace=true