global:
  domain: argocd.khalin.local

argo-cd:
  configs:
    params:
      server.insecure: true

  notifications:
    enabled: false

  certificate:
    enabled: true

  server:
    ingress:
      enabled: true
